### ISSUE TITLE
Add info on how to add a pagebreak to a document.

### ISSUE THREAD

**Issue by raphaelquast** [executablebooks/mystmd#958] opened 2024-03-06 13:55 UTC
### Describe the gap in the current documentation

Not sure if I missed this somehow, but I simply can't find any information on how I can tell an export with `myst build ...` to insert a pagebreak at a specific location in my markdown file.

### Describe the solution you'd like

I'd like some information on how to add a pagebreak to a file (specifically for export from `markdown` to `docx`) 

None of the following worked so far:

html-breaks don't work as expected
```
<p style="page-break-before: always"> &nbsp; 
<div> style="page-break-after: always"> &nbsp; </div>
<div> style="page-break-before: always"> &nbsp; </div>
```
latex-commands are just printed as text...
```
\newpage
\clearpage
\pagebreak
```

**Comment by rowanc1** [comment] 2024-04-05 04:49
Thanks @raphaelquast - closing this as a duplicate of #714. Planning to get this done in the coming week.

**Closed by rowanc1** 2024-04-05 04:49 UTC
Labels: documentation

**Comment by rowanc1** [comment] 2024-04-19 18:33
This will be possible in the next release of MyST!

```
+++ {"page-break": true}
```

**Comment by raphaelquast** [comment] 2024-04-19 22:06
Awesome! Thanks for the quick implementation!

**Comment by rowanc1** [comment] 2024-04-19 22:18
Let us know how it works, should be released now! 🚀
